<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SUGGESTIONS</name>
   <tag></tag>
   <elementGuidId>583b9677-9569-46ad-b7fe-72d574280c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-autowhatever-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-autowhatever-1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'react-autowhatever-1' and @role = 'listbox' and @class = 'react-autosuggest__suggestions-container react-autosuggest__suggestions-container--open']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-autowhatever-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-autosuggest__suggestions-container react-autosuggest__suggestions-container--open</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SUGGESTIONS Delhi, India Delhi AirportDELMore CitiesGhaziabad, India HindonVDX25 KMs away from Delhi, IndiaToronto, Canada Lester B. Pearson International AirportYYZ133 KMs away from Delhi, CanadaMonroe, United States Monroe Regional AirportMLU60 KMs away from Delhi, United StatesThorndale, Canada London AirportYXU60 KMs away from Delhi, CanadaHamilton, Canada John C. Munro Hamilton International AirportYHM62 KMs away from Delhi, CanadaWaterloo, Canada Waterloo AirportYKF70 KMs away from Delhi, CanadaToronto, Canada Buttonville Municipal AirportYKZ133 KMs away from Delhi, CanadaToronto, Canada Toronto - All AirportsYTO133 KMs away from Delhi, CanadaToronto, Canada Billy Bishop Toronto City Centre AirportYTZ133 KMs away from Delhi, CanadaToronto, Canada Toronto Downtown AirportYBZ133 KMs away from Delhi, Canada</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-autowhatever-1&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-autowhatever-1']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEL, Delhi Airport India'])[1]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From'])[1]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
